name: Daily TW Market Update

on:
  schedule:
    # 18:30 Asia/Taipei == 10:30 UTC
    - cron: '30 10 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install yfinance pandas pyarrow requests

      - name: Run updater
        run: |
          python data_updater.py

      - name: Commit and push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "Daily market data update" || echo "No changes to commit"
          git push

